### ISSUE TITLE
Attribute Conversion: Descs and Rooms (Initial)

### ISSUE THREAD

**Issue by dvoraen** [Arx-Game/arxcode#450]
## Overview
This is for tracking the issues and/or tasks related to refactoring desc storage and room attributes.

## Goal
Eliminate an estimated 150k rows from the attribute table.

## Tasks
**Items listed on this task list are a work in progress (more to be added, modified, etc.).**
- [ ] Collate type list of objects that use DescMixins for storing desc data.
- [ ] Write models
  - [ ] room data (desc, seasonal desc, banlist, and so on)
- [ ] ? Refactor object_extensions to include new data models (change to object_extensions/models/*.py?)
- [ ] Refactor DescMixins to use model(s) data
- [ ] Modify methods of relevant typeclasses, if needed (e.g. `at_*_creation()`)
- [ ] Refactor commands:
  - [ ] CmdDig
  - [ ] CmdBuildRoom (data initialization upon creation)
  - [ ] CmdManageRoom (e.g. banlist, seasonal descs)
- [ ] Add app to INSTALLED_APPS if necessary

**Comment by dvoraen** [comment]
Copied over to my fork.  Closing this.
